In [176]:
import numpy as np
import pandas as pd
import re
import seaborn as sns
import matplotlib.pyplot as plt
from nltk.corpus import stopwords # remove-->the,for,of,in,with
from nltk.stem.porter import PorterStemmer # Loved or Loving-->love
from sklearn.feature_extraction.text import TfidfVectorizer # Loved = [0.0]
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression 
from sklearn.metrics import accuracy_score
import string

In [177]:
df_fake = pd.read_csv('Fake (1).csv')

In [178]:
df_true = pd.read_csv('True.csv')

In [179]:
df_fake.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [180]:
df_true.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [181]:
df_fake["class"] = 0
df_true["class"] = 1

In [182]:
df_fake.shape,df_true.shape

((23481, 5), (21417, 5))

In [183]:
df_fake_manual_testing = df_fake.tail(10)
for i in range(23480, 23470, -1):
    df_fake.drop([i], axis=0, inplace=True)

df_true_manual_testing = df_true.tail(10)
for i in range(21416, 21406, -1):
    df_true.drop([i], axis=0, inplace=True)

In [184]:
df_fake.shape,df_true.shape

((23471, 5), (21407, 5))

In [185]:
df_fake_manual_testing['class'] = 0
df_true_manual_testing['class'] = 1

C:\Users\Kajal\AppData\Local\Temp\ipykernel_6952\1523065411.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fake_manual_testing['class'] = 0
C:\Users\Kajal\AppData\Local\Temp\ipykernel_6952\1523065411.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_true_manual_testing['class'] = 1

In [186]:
df_fake_manual_testing.head(10)

,title,text,subject,date,class
23471,Seven Iranians freed in the prisoner swap have...,"21st Century Wire says This week, the historic...",Middle-east,"January 20, 2016",0
23472,#Hashtag Hell & The Fake Left,By Dady Chery and Gilbert MercierAll writers ...,Middle-east,"January 19, 2016",0
23473,Astroturfing: Journalist Reveals Brainwashing ...,Vic Bishop Waking TimesOur reality is carefull...,Middle-east,"January 19, 2016",0
23474,The New American Century: An Era of Fraud,Paul Craig RobertsIn the last years of the 20t...,Middle-east,"January 19, 2016",0
23475,Hillary Clinton: ‘Israel First’ (and no peace ...,Robert Fantina CounterpunchAlthough the United...,Middle-east,"January 18, 2016",0
23476,McPain: John McCain Furious That Iran Treated ...,21st Century Wire says As 21WIRE reported earl...,Middle-east,"January 16, 2016",0
23477,JUSTICE? Yahoo Settles E-mail Privacy Class-ac...,21st Century Wire says It s a familiar theme. ...,Middle-east,"January 16, 2016",0
23478,Sunnistan: US and Allied ‘Safe Zone’ Plan to T...,Patrick Henningsen 21st Century WireRemember ...,Middle-east,"January 15, 2016",0
23479,How to Blow $700 Million: Al Jazeera America F...,21st Century Wire says Al Jazeera America will...,Middle-east,"January 14, 2016",0
23480,10 U.S. Navy Sailors Held by Iranian Military ...,21st Century Wire says As 21WIRE predicted in ...,Middle-east,"January 12, 2016",0

In [187]:
df_true_manual_testing.head(10)

,title,text,subject,date,class
21407,"Mata Pires, owner of embattled Brazil builder ...","SAO PAULO (Reuters) - Cesar Mata Pires, the ow...",worldnews,"August 22, 2017",1
21408,"U.S., North Korea clash at U.N. forum over nuc...",GENEVA (Reuters) - North Korea and the United ...,worldnews,"August 22, 2017",1
21409,"U.S., North Korea clash at U.N. arms forum on ...",GENEVA (Reuters) - North Korea and the United ...,worldnews,"August 22, 2017",1
21410,Headless torso could belong to submarine journ...,COPENHAGEN (Reuters) - Danish police said on T...,worldnews,"August 22, 2017",1
21411,North Korea shipments to Syria chemical arms a...,UNITED NATIONS (Reuters) - Two North Korean sh...,worldnews,"August 21, 2017",1
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017",1
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017",1
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017",1
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017",1
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017",1

In [188]:
df_merge = pd.concat([df_fake,df_true])
df_merge.head(10)

,title,text,subject,date,class
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0
5,Racist Alabama Cops Brutalize Black Boy While...,The number of cases of cops brutalizing and ki...,News,"December 25, 2017",0
6,"Fresh Off The Golf Course, Trump Lashes Out A...",Donald Trump spent a good portion of his day a...,News,"December 23, 2017",0
7,Trump Said Some INSANELY Racist Stuff Inside ...,In the wake of yet another court decision that...,News,"December 23, 2017",0
8,Former CIA Director Slams Trump Over UN Bully...,Many people have raised the alarm regarding th...,News,"December 22, 2017",0
9,WATCH: Brand-New Pro-Trump Ad Features So Muc...,Just when you might have thought we d get a br...,News,"December 21, 2017",0

In [189]:
df_merge.shape

(44878, 5)

In [190]:
df_merge.columns

Index(['title', 'text', 'subject', 'date', 'class'], dtype='object')

In [191]:
data =  df_merge.drop(['title','subject','date'],axis = 1)

In [192]:
data.isnull().sum()

text     0
class    0
dtype: int64

In [193]:
data.reset_index(inplace = True)
data.drop(['index'],axis = 1,inplace = True)

In [194]:
data.columns

Index(['text', 'class'], dtype='object')

In [195]:
data.head()

                                                text  class
0  Donald Trump just couldn t wish all Americans ...      0
1  House Intelligence Committee Chairman Devin Nu...      0
2  On Friday, it was revealed that former Milwauk...      0
3  On Christmas day, Donald Trump announced that ...      0
4  Pope Francis used his annual Christmas Day mes...      0

In [196]:
data.head()

                                                text  class
0  Donald Trump just couldn t wish all Americans ...      0
1  House Intelligence Committee Chairman Devin Nu...      0
2  On Friday, it was revealed that former Milwauk...      0
3  On Christmas day, Donald Trump announced that ...      0
4  Pope Francis used his annual Christmas Day mes...      0

In [197]:
print(data['text'].dtype)
print(data['text'].head())

object
0    Donald Trump just couldn t wish all Americans ...
1    House Intelligence Committee Chairman Devin Nu...
2    On Friday, it was revealed that former Milwauk...
3    On Christmas day, Donald Trump announced that ...
4    Pope Francis used his annual Christmas Day mes...
Name: text, dtype: object

In [198]:
print(data['text'].isna().sum())

0

In [199]:
data.head()

                                                text  class
0  Donald Trump just couldn t wish all Americans ...      0
1  House Intelligence Committee Chairman Devin Nu...      0
2  On Friday, it was revealed that former Milwauk...      0
3  On Christmas day, Donald Trump announced that ...      0
4  Pope Francis used his annual Christmas Day mes...      0

In [237]:
data["text"][0]

'donald trump just couldn t wish all americans a happy new year and leave it at that  instead  he had to give a shout out to his enemies  haters and  the very dishonest fake news media   the former reality show star had just one job to do and he couldn t do it  as our country rapidly grows stronger and smarter  i want to wish all of my friends  supporters  enemies  haters  and even the very dishonest fake news media  a happy and healthy new year   president angry pants tweeted    will be a great year for america  as our country rapidly grows stronger and smarter  i want to wish all of my friends  supporters  enemies  haters  and even the very dishonest fake news media  a happy and healthy new year   will be a great year for america   donald j  trump   realdonaldtrump  december    s tweet went down about as welll as you d expect what kind of president sends a new year s greeting like this despicable  petty  infantile gibberish  only trump  his lack of decency won t even allow him to rise above the gutter long enough to wish the american citizens a happy new year   bishop talbert swan   talbertswan  december    one likes you  calvin   calvinstowell  december    impeachment would make  a great year for america  but i ll also accept regaining control of congress   miranda yaver   mirandayaver  december    you hear yourself talk  when you have to include that many people that hate you you have to wonder  why do the they all hate me   alan sandoval     december    uses the word haters in a new years wish    marlene     december    can t just say happy new year   koren pollitt   korencarpenter  december    s trump s new year s eve tweet from  happy new year to all  including to my many enemies and those who have fought me and lost so badly they just don t know what to do  love   donald j  trump   realdonaldtrump  december    is nothing new for trump  he s been doing this for years trump has directed messages to his  enemies  and  haters  for new year s  easter  thanksgiving  and the anniversary of    pic twitter com   daniel dale     december    s holiday tweets are clearly not presidential how long did he work at hallmark before becoming president   steven goodine   sgoodine  december    s always been like this       the only difference is that in the last few years  his filter has been breaking down   roy schulze   thbthttt  december     apart from a teenager uses the term haters   wendy   wendywhistles  december    s a fucking  year old  who knows     december     to all the people who voted for this a hole thinking he would change once he got into power  you were wrong   year old men don t change and now he s a year older photo by andrew burton getty images '

In [238]:
data

                                                    text  class
0      donald trump just couldn t wish all americans ...      0
1      house intelligence committee chairman devin nu...      0
2      on friday  it was revealed that former milwauk...      0
3      on christmas day  donald trump announced that ...      0
4      pope francis used his annual christmas day mes...      0
...                                                  ...    ...
44873  on board a u s  military aircraft  reuters    ...      1
44874  washington  reuters    the united states sugge...      1
44875  washington  reuters    the united states has d...      1
44876  islamabad  reuters    outlining a new strategy...      1
44877  geneva  reuters    north korea and the united ...      1

[44878 rows x 2 columns]

In [201]:
import re
import string

def worddopt(text):
    text = text.lower()
    text = re.sub(r'\[.*?\]', '', text)
    text = re.sub(r"\W", " ", text)
    text = re.sub(r'https?://\S+|www\.\S+', '', text)
    text = re.sub(r'<.*?>+', '', text)
    text = re.sub(r'[%s]' % re.escape(string.punctuation), '', text)
    text = re.sub(r'\n', '', text)
    text = re.sub(r'\w*\d\w*', '', text)
    return text

In [202]:
data['text'] = data['text'].apply(worddopt)

In [203]:
data

                                                    text  class
0      donald trump just couldn t wish all americans ...      0
1      house intelligence committee chairman devin nu...      0
2      on friday  it was revealed that former milwauk...      0
3      on christmas day  donald trump announced that ...      0
4      pope francis used his annual christmas day mes...      0
...                                                  ...    ...
44873  on board a u s  military aircraft  reuters    ...      1
44874  washington  reuters    the united states sugge...      1
44875  washington  reuters    the united states has d...      1
44876  islamabad  reuters    outlining a new strategy...      1
44877  geneva  reuters    north korea and the united ...      1

[44878 rows x 2 columns]

In [204]:
x = data['text']
y = data['class']

In [205]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25)

In [206]:
pip install --upgrade scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: scikit-learn in c:\users\kajal\appdata\roaming\python\python312\site-packages (1.9.0)
Requirement already satisfied: numpy>=1.24.1 in c:\users\kajal\appdata\roaming\python\python312\site-packages (from scikit-learn) (2.5.1)
Requirement already satisfied: scipy>=1.10.0 in c:\users\kajal\appdata\roaming\python\python312\site-packages (from scikit-learn) (1.18.0)
Requirement already satisfied: joblib>=1.4.0 in c:\programdata\anaconda3\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: narwhals>=2.0.1 in c:\users\kajal\appdata\roaming\python\python312\site-packages (from scikit-learn) (2.18.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\programdata\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)
Note: you may need to restart the kernel to use updated packages.

In [207]:
import sys
!C:\ProgramData\anaconda3\python.exe -m pip install --upgrade scikit-learn scipy numpy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: scikit-learn in c:\users\kajal\appdata\roaming\python\python312\site-packages (1.9.0)
Requirement already satisfied: scipy in c:\users\kajal\appdata\roaming\python\python312\site-packages (1.18.0)
Requirement already satisfied: numpy in c:\users\kajal\appdata\roaming\python\python312\site-packages (2.5.1)
Requirement already satisfied: joblib>=1.4.0 in c:\programdata\anaconda3\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: narwhals>=2.0.1 in c:\users\kajal\appdata\roaming\python\python312\site-packages (from scikit-learn) (2.18.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\programdata\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)

In [208]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorization = TfidfVectorizer()
xv_train = vectorization.fit_transform(x_train)
xv_test = vectorization.transform(x_test)

In [211]:
xv_train,xv_test

(<33658x95193 sparse matrix of type '<class 'numpy.float64'>'
 	with 6895094 stored elements in Compressed Sparse Row format>,
 <11220x95193 sparse matrix of type '<class 'numpy.float64'>'
 	with 2290352 stored elements in Compressed Sparse Row format>)

In [209]:
print(data['text'].isnull().sum())

0

In [212]:
from sklearn.linear_model import LogisticRegression

LR = LogisticRegression()
LR.fit(xv_train,y_train)

LogisticRegression()

In [213]:
pred_lr = LR.predict(xv_test)

In [214]:
LR.score(xv_test,y_test)

0.986541889483066

In [219]:
print(classification_report(y_test,pred_lr))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      5851
           1       0.98      0.99      0.99      5369

    accuracy                           0.99     11220
   macro avg       0.99      0.99      0.99     11220
weighted avg       0.99      0.99      0.99     11220

In [220]:
from sklearn.tree import DecisionTreeClassifier

DT = DecisionTreeClassifier()
DT.fit(xv_train,y_train)

DecisionTreeClassifier()

In [221]:
pred_dt = DT.predict(xv_train)

In [222]:
DT.score(xv_test,y_test)

0.9942067736185384

In [223]:
from sklearn.ensemble import GradientBoostingClassifier

GB = GradientBoostingClassifier(random_state = 0)
GB.fit(xv_train,y_train)

GradientBoostingClassifier(random_state=0)

In [225]:
predit_gb = GB.predict(xv_test)

In [226]:
GB.score(xv_test,y_test)

0.9945632798573975

In [228]:
print(classification_report(y_test,predit_gb))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99      5851
           1       0.99      1.00      0.99      5369

    accuracy                           0.99     11220
   macro avg       0.99      0.99      0.99     11220
weighted avg       0.99      0.99      0.99     11220

In [230]:
from sklearn.ensemble import RandomForestClassifier

rfc = GradientBoostingClassifier()
rfc.fit(xv_train,y_train)

GradientBoostingClassifier()

In [232]:
rfc_pred = rfc.predict(xv_test)

In [233]:
print(classification_report(y_test,rfc_pred))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99      5851
           1       0.99      1.00      0.99      5369

    accuracy                           0.99     11220
   macro avg       0.99      0.99      0.99     11220
weighted avg       0.99      0.99      0.99     11220

In [243]:
def output_label(n):
    if n == 0:
        return "Fake News"
    elif n == 1:
        return "Not A Fake News"


def manual_testing(news):

    testing_news = {"text": [news]}

    new_def_test = pd.DataFrame(testing_news)

    new_def_test["text"] = new_def_test["text"].apply(worddopt)

    new_x_test = new_def_test["text"]

    new_xv_test = vectorization.transform(new_x_test)

    pred_LR = LR.predict(new_xv_test)
    pred_DT = DT.predict(new_xv_test)
    pred_GBC = GB.predict(new_xv_test)
    pred_RFC = rfc.predict(new_xv_test)

    return (
        f"\n\nLR Prediction : {output_label(pred_LR[0])}"
        f"\nDT Prediction : {output_label(pred_DT[0])}"
        f"\nGBC Prediction : {output_label(pred_GBC[0])}"
        f"\nRFC Prediction : {output_label(pred_RFC[0])}"
    )

In [244]:
news = input("Enter News: ")

print(manual_testing(news))

Enter News:   'donald trump just couldn t wish all americans a happy new year and leave it at that  instead  he had to give a shout out to his enemies  haters and  the very dishonest fake news media   the former reality show star had just one job to do and he couldn t do it  as our country rapidly grows stronger and smarter  i want to wish all of my friends  supporters  enemies  haters  and even the very dishonest fake news media  a happy and healthy new year   president angry pants tweeted    will be a great year for america  as our country rapidly grows stronger and smarter  i want to wish all of my friends  supporters  enemies  haters  and even the very dishonest fake news media  a happy and healthy new year   will be a great year for america   donald j  trump   realdonaldtrump  december    s tweet went down about as welll as you d expect what kind of president sends a new year s greeting like this despicable  petty  infantile gibberish  only trump  his lack of decency won t even allow him to rise above the gutter long enough to wish the american citizens a happy new year   bishop talbert swan   talbertswan  december    one likes you  calvin   calvinstowell  december    impeachment would make  a great year for america  but i ll also accept regaining control of congress   miranda yaver   mirandayaver  december    you hear yourself talk  when you have to include that many people that hate you you have to wonder  why do the they all hate me   alan sandoval     december    uses the word haters in a new years wish    marlene     december    can t just say happy new year   koren pollitt   korencarpenter  december    s trump s new year s eve tweet from  happy new year to all  including to my many enemies and those who have fought me and lost so badly they just don t know what to do  love   donald j  trump   realdonaldtrump  december    is nothing new for trump  he s been doing this for years trump has directed messages to his  enemies  and  haters  for new year s  easter  thanksgiving  and the anniversary of    pic twitter com   daniel dale     december    s holiday tweets are clearly not presidential how long did he work at hallmark before becoming president   steven goodine   sgoodine  december    s always been like this       the only difference is that in the last few years  his filter has been breaking down   roy schulze   thbthttt  december     apart from a teenager uses the term haters   wendy   wendywhistles  december    s a fucking  year old  who knows     december     to all the people who voted for this a hole thinking he would change once he got into power  you were wrong   y

LR Prediction : Fake News
DT Prediction : Fake News
GBC Prediction : Fake News
RFC Prediction : Fake News

In [245]:
import pickle
pickle.dump(LR,open("model.pkl","wb"))
pickle.dump(vectorization,open("vectorizer.pkl","wb"))